default: true

# Turn off specific rules that you don't want to enforce
MD013: false # Line length
MD031: false # Blank lines around fenced code blocks
MD036: false # Emphasis used instead of heading
MD047: false # Files should end with a single newline character