site_name: Documentation Portal | Sheethal U
theme:
  name: material
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - content.code.copy

plugins:
  - search
  - swagger-ui-tag:
      path_type:

nav:
  - Welcome: index.md
  - Project Overview: project-intro.md
  - API Reference:
    - Authentication: auth/login.md
    - Search API: search/search-loans.md
    - Sorting: sorting/sorting.md
    - Dropdowns: dropdown/dropdowns.md
    - Error Codes: Errors/errors.md
  - Resources & Downloads: resources.md

markdown_extensions:
  - attr_list

